/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Platform = IDL.Variant({
  'flipkart' : IDL.Null,
  'other' : IDL.Text,
  'amazon' : IDL.Null,
  'blinkit' : IDL.Null,
  'meesho' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'productUrl' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'platform' : Platform,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, Platform, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getProductsByPlatform' : IDL.Func([Platform], [IDL.Vec(Product)], ['query']),
  'searchProducts' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(Platform)],
      [IDL.Vec(Product)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Platform = IDL.Variant({
    'flipkart' : IDL.Null,
    'other' : IDL.Text,
    'amazon' : IDL.Null,
    'blinkit' : IDL.Null,
    'meesho' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'productUrl' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'platform' : Platform,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, Platform, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByPlatform' : IDL.Func(
        [Platform],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'searchProducts' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(Platform)],
        [IDL.Vec(Product)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };