/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Platform = { 'flipkart' : null } |
  { 'other' : string } |
  { 'amazon' : null } |
  { 'blinkit' : null } |
  { 'meesho' : null };
export interface Product {
  'id' : bigint,
  'productUrl' : string,
  'name' : string,
  'description' : string,
  'platform' : Platform,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [string, bigint, string, string, string, Platform, string],
    bigint
  >,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getProductsByPlatform' : ActorMethod<[Platform], Array<Product>>,
  'searchProducts' : ActorMethod<
    [string, [] | [string], [] | [Platform]],
    Array<Product>
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];